```yaml
# permissions for end users to view sharedrdms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: migration
    app.kubernetes.io/managed-by: kustomize
  