# permissions for end users to edit sharedrdms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: migration
    app.kubernetes.io/managed-by: kustomize
  name: sharedrdm-editor-role
rules:
- apiGroups:
  - vjailbreak.k8s.pf9.io
  resources:
  - sharedrdms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vjailbreak.k8s.pf9.io
  resources:
  - sharedrdms/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list